# Generated by Django 4.2.11 on 2024-04-29 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_category_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 29, 17, 1, 3, 703690, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 29, 17, 1, 3, 703199, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 29, 17, 1, 3, 703525, tzinfo=datetime.timezone.utc)),
        ),
    ]
