# Generated by Django 4.2.11 on 2024-04-29 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_subscriber_alter_category_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='category',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 29, 17, 27, 50, 380665, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 29, 17, 27, 50, 380974, tzinfo=datetime.timezone.utc)),
        ),
    ]
